apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-a
  namespace: spring-a
  labels:
    app: spring-a
    app.kubernetes.io/name: keda-spring
    app.kubernetes.io/managed-by: keda
    keda-enabled: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-a
  template:
    metadata:
      labels:
        app: spring-a
        app.kubernetes.io/name: keda-spring
        app.kubernetes.io/managed-by: keda
        keda-enabled: "true"        
    spec:
      terminationGracePeriodSeconds: 40    
      containers:
      - name: spring-a
        image: dev.local/spring-a:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: APP_NAME
          value: spring-a
        - name: SPRING_URL
          value: spring-b.spring-b.svc.cluster.local:8080
        - name: OTEL_SERVICE_NAME
          value: spring-a
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        - name: OTEL_LOGS_EXPORTER
          value: otlp        
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
---
apiVersion: v1
kind: Service
metadata:
  name: spring-a-service
  namespace: spring-a
  labels:
    app: spring-a
    app.kubernetes.io/name: keda-spring
    app.kubernetes.io/managed-by: keda
    keda-enabled: "true"
spec:
  selector:
    app: spring-a
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort