apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: logging
  labels:
    grafana_datasource: "true"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki.logging.svc.cluster.local:3100
        access: proxy
        isDefault: true

      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3100
        jsonData:
          tracesToLogsV2:
            datasourceUid: 'loki'
            spanStartTimeShift: '-5m'
            spanEndTimeShift: '5m'
            tags: ['job', 'instance']

      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.logging.svc.cluster.local
        isDefault: true