loki:
  enabled: true
  service:
    type: LoadBalancer
    port: 3100
    annotations:
      service.beta.kubernetes.io/ncloud-load-balancer-subnet-id: "34873"
  readinessProbe:
    httpGet:
      path: /ready
      port: 3100
  livenessProbe:
    httpGet:
      path: /ready
      port: 3100

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
    snippets:
      pipeline_stages:
        - docker: {}