loki:
  enabled: true
  config:
    auth_enabled: false
    target: all
    chunk_store_config:
      max_look_back_period: 0s
    compactor:
      shared_store: filesystem
      working_directory: /data/loki/boltdb-shipper-compactor
    ingester:
      chunk_target_size: 524288
      chunk_block_size: 262144
      chunk_idle_period: 1m
      chunk_retain_period: 30s
      max_chunk_age: 10m
      lifecycler:
        ring:
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: /data/loki/wal
    limits_config:
      retention_period: 2400h
      enforce_metric_name: false
      max_entries_limit_per_query: 100000
      reject_old_samples: false
      reject_old_samples_max_age: 168h
      max_query_length: 0h
    memberlist:
      join_members:
      - loki-stack-memberlist
    schema_config:
      configs:
      - from: "2020-10-24"
        index:
          period: 24h
          prefix: index_
        object_store: filesystem
        schema: v11
        store: boltdb-shipper
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
    query_range:
      split_queries_by_interval: 0
      parallelise_shardable_queries: false
    querier:
      max_concurrent: 2048
    frontend:
      max_outstanding_per_tenant: 4096
      compress_responses: true
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h  
  image:
    tag: 2.9.3
  service:
    type: NodePort

promtail:
  enabled: true
  extraArgs:
    - -config.expand-env=true
  config:
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
        batchsize: 2097152    # 2MB
        batchwait: 1s
    server:
      queue_size: 1000        # 최대 큐 크기(=배치 실패시 1000개만 쌓이고 그 이상 drop)
      snippets:
        scrapeConfigs:  |
          # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
          - job_name: kubernetes-pods
            pipeline_stages:
              - drop:
                  expression: '(.{2097152,})'  // 2MB 넘는 라인은 미리 drop            
              - cri: {}
              - regex:
                  expression: '\[LOG_FOR_APP\]:(?P<json>\{.*\})'
              - json:
                  expressions:
                    uuid: uuid 
                  source: json
              - labels:
                  uuid:
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - action: drop
                source_labels: [__meta_kubernetes_pod_label_app]
                regex: aidt-apm
              - source_labels:
                  - __meta_kubernetes_pod_controller_name
                regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                action: replace
                target_label: __tmp_controller_name
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_name
                  - __meta_kubernetes_pod_label_app
                  - __tmp_controller_name
                  - __meta_kubernetes_pod_name
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: app
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_instance
                  - __meta_kubernetes_pod_label_instance
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: instance
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_component
                  - __meta_kubernetes_pod_label_component
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: component
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_node_name
                target_label: node_name
              - action: replace
                source_labels:
                - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                replacement: $1
                separator: /
                source_labels:
                - namespace
                - app
                target_label: job
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_name
                target_label: pod
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_container_name
                target_label: container
              - action: replace
                replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
                target_label: __path__
              - action: replace
                regex: true/(.*)
                replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels:
                - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
                - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
                - __meta_kubernetes_pod_container_name
                target_label: __path__

fluent-bit:
  enabled: false

grafana:
  enabled: true
  sidecar:
    datasources:
      label: grafana_datasource
      labelValue: "true"
      enabled: false
      maxLines: 1000
  image:
    tag: 10.3.3
  service:
    type: NodePort

prometheus:
  enabled: true
  isDefault: true
  url: http://{{ include "prometheus.fullname" .}}:{{ .Values.prometheus.server.service.servicePort }}{{ .Values.prometheus.server.prefixURL }}
# url: http://prometheus-server.monitoring.svc.cluster.local
  datasource:
    jsonData: "{}"
  server:
    service:
      type: NodePort
    extraArgs:
      enable-feature: remote-write-receiver
    extraScrapeConfigs: |
      - job_name: 'keda-operator-metrics-apiserver'
        scrape_interval: 10s
        static_configs:
          - targets:
              - keda-operator-metrics-apiserver.keda.svc.cluster.local:8080
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['loki-kube-state-metrics.logging.svc.cluster.local:8080']

filebeat:
  enabled: false

logstash:
  enabled: false