loki:
  enabled: true
  isDefault: true

promtail:
  enabled: true

fluent-bit:
  enabled: false

grafana:
  enabled: true

prometheus:
  enabled: true
  isDefault: false
  url: http://{{ include "prometheus.fullname" .}}:{{ .Values.prometheus.server.service.servicePort }}{{ .Values.prometheus.server.prefixURL }}
# url: http://prometheus-server.monitoring.svc.cluster.local
  datasource:
    jsonData: "{}"

filebeat:
  enabled: false

logstash:
  enabled: false