loki:
  enabled: true
  existingSecret: loki-config
  isDefault: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"
  image:
    tag: 2.9.3
  service:
    type: NodePort

promtail:
  enabled: true
  extraArgs:
    - -config.expand-env=true
  config:
    snippets:
      extraRelabelConfigs:
        - action: replace
          source_labels: [__meta_kubernetes_pod_name]
          target_label: service_name
        - action: replace
          source_labels: [__meta_kubernetes_namespace]
          target_label: service_namespace
        - action: replace
          source_labels: [__meta_kubernetes_pod_label_deployment_environment_name]
          target_label: deployment_environment_name

fluent-bit:
  enabled: false

grafana:
  enabled: true
  sidecar:
    datasources:
      label: grafana_datasource
      labelValue: "true"
      enabled: true
      maxLines: 1000
  image:
    tag: 10.3.3
  service:
    type: NodePort

prometheus:
  enabled: true
  isDefault: true
  url: http://{{ include "prometheus.fullname" .}}:{{ .Values.prometheus.server.service.servicePort }}{{ .Values.prometheus.server.prefixURL }}
# url: http://prometheus-server.monitoring.svc.cluster.local
  datasource:
    jsonData: "{}"
  server:
    service:
      type: NodePort
    extraArgs:
      enable-feature: remote-write-receiver
    extraScrapeConfigs: |
      - job_name: 'keda-operator-metrics-apiserver'
        scrape_interval: 10s
        static_configs:
          - targets:
              - keda-operator-metrics-apiserver.keda.svc.cluster.local:8080
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['loki-kube-state-metrics.logging.svc.cluster.local:8080']

filebeat:
  enabled: false

logstash:
  enabled: false