loki:
  enabled: true
  isDefault: true
  image:
    tag: 2.9.3
  service:
    type: NodePort

promtail:
  enabled: true

fluent-bit:
  enabled: false

grafana:
  enabled: true
  sidecar:
    datasources:
      label: grafana_datasource
      labelValue: "true"
      enabled: true
      maxLines: 1000
  image:
    tag: 10.3.3
  service:
    type: NodePort

prometheus:
  enabled: true
  isDefault: false
  url: http://{{ include "prometheus.fullname" .}}:{{ .Values.prometheus.server.service.servicePort }}{{ .Values.prometheus.server.prefixURL }}
# url: http://prometheus-server.monitoring.svc.cluster.local
  datasource:
    jsonData: "{}"
  server:
    service:
      type: NodePort

filebeat:
  enabled: false

logstash:
  enabled: false