apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-io
  namespace: spring-io
  labels:
    app: spring-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-io
  template:
    metadata:
      labels:
        app: spring-io
    spec:
      containers:
      - name: spring-io
        image: local/spring-io:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: spring-io-service
  namespace: spring-io
spec:
  selector:
    app: spring-io
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-io-ingress
  namespace: spring-io
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: ing-shared-alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-certificate-no: "40463"  
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/actions.spring-io-service: >
      {"type":"targetGroup","targetGroup":{"targetGroups":[{"serviceName":"spring-io/spring-io","servicePort":80,"weight":100}]}}
spec:
  ingressClassName: alb
  tls:
    - hosts:
        - spring.hav-ing.store
  rules:
  - host: spring.hav-ing.store  # 실제 도메인으로 변경 필요
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-io-service
            port:
              name: use-annotation
