apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: spring-io-scaler
spec:
  scaleTargetRef:
    name: spring-io
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: http
    metadata:
      targetPendingRequests: "100"
      activationTargetPendingRequests: "50"
