apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: spring-io-scaler
  namespace: spring-io
spec:
  scaleTargetRef:
    name: spring-io
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: http
    metadata:
      targetPendingRequests: "100"
      activationTargetPendingRequests: "50"
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.monitoring.svc:9090
      metricName: http_requests_per_second
      query: |
        sum(rate(http_requests_total{job="your-app"}[1m]))
      threshold: "1000"
  - type: cpu
    metadata:
      type: Utilization
      value: "60"      
