apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: spring-io-scaler
  namespace: spring-io
spec:
  scaleTargetRef:
    name: spring-io
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:

    # Prometheus + Micrometer (Spring Boot)
    - type: prometheus
      metadata:
        metricName: http_pending_requests 
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local
        metricName: spring_http_requests_per_second
        query: |
          sum(
            rate(http_server_requests_seconds_count{
              application="spring-io", 
              uri!="/actuator/health"
            }[1m])
          )
        threshold: "10"  # 초당 10 요청이면 스케일링

    # CPU scaler (백업용)
    - type: cpu
      metadata:
        metricName: spring_io_cpu_utilization 
        type: Utilization
        value: "60"

    # Cron-based scaling - scale up to 5
    - type: cron
      metadata:
        name: scale-up-cron
        timezone: Asia/Seoul
        start: "0 */5 * * *"       # 매 5분 0초
        end: "1 */5 * * *"         # 매 5분 1초
        desiredReplicas: "5"        

    # Cron-based scaling - reset back to minReplicaCount
    - type: cron
      metadata:
        name: scale-down-cron
        timezone: Asia/Seoul
        start: "1 */5 * * *"       # 매 5분 1초
        end: "2 */5 * * *"         # 매 5분 2초
        desiredReplicas: "1"

status:
  externalMetricNames:
    - spring_http_requests_per_second
    - spring_io_cpu_utilization