service:
  type: NodePort
alloy:
  configMap:
    create: true
    content: |
      promtail.scrape "spring-io-log" {
        targets = [
          {
            __address__ = "localhost"
            __path__ = "/var/log/containers/*spring-io*.log"
          }
        ]
        pipeline_stage {
          drop {
            expression = "^(?!.*\\[LOG_FOR_APP\\]).*$"
          }
        }
        forward_to = [loki.write.loki1.receiver]
      }

      promtail.scrape "spring-io-other" {
        targets = [
          {
            __address__ = "localhost"
            __path__ = "/var/log/containers/*spring-io*.log"
          }
        ]
        pipeline_stage {
          drop {
            expression = ".*\\[LOG_FOR_APP\\].*"
          }
        }
        forward_to = [loki.write.loki2.receiver]
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }

      loki.write "loki1" {
        endpoint {
          url = "http://loki.logging:3100/loki/api/v1/push"
        }
      }

      loki.write "loki2" {
        endpoint {
          url = "http://loki-distributed-gateway.logging:3100/loki/api/v1/push"
        }
      }        
  mounts:
    varlog: true      