service:
  type: NodePort
alloy:
  configMap:
    create: true
    content: |
      loki.source.file "log_for_app" {
        targets = [
          { __path__ = "/var/log/containers/*spring-io*.log" }
        ]
        selector {
          include = ["*LOG_FOR_APP*"]
        }
        forward_to = [loki.write.loki_b.receiver]
      }

      loki.source.file "other_logs" {
        targets = [
          { __path__ = "/var/log/containers/*spring-io*.log" }
        ]
        selector {
          exclude = ["*LOG_FOR_APP*"]
        }
        forward_to = [loki.write.loki_a.receiver]
      }

      loki.write "loki_a" {
        endpoint {
          url = "http://loki.logging:3100/loki/api/v1/push"
        }
      }

      loki.write "loki_b" {
        endpoint {
          url = "http://loki-distributed-gateway.logging:3100/loki/api/v1/push"
        }
      }
  mounts:
    varlog: true      