service:
  type: NodePort
alloy:
  configMap:
    create: true
    # 여기다 Alloy config를 넣음 (indentation 주의! | 반드시 필요)
    content: |
      local.file_match "spring_io_logs" {
        path = "/var/log/containers/*spring-io*.log"
      }

      processors.regex "has_log_for_app" {
        expression = "\\[LOG_FOR_APP\\]"
        input      = local.file_match.spring_io_logs.output
      }
      processors.regex "not_log_for_app" {
        expression = "^(?!.*\\[LOG_FOR_APP\\]).*$"
        input      = local.file_match.spring_io_logs.output
      }

      loki.write "loki_a" {
        endpoint {
          url = "http://loki.logging:3100/loki/api/v1/push"
        }
      }
      loki.write "loki_b" {
        endpoint {
          url = "http://loki-distributed-gateway.logging:3100/loki/api/v1/push"
        }
      }

      route "log_for_app_to_loki_b" {
        input  = processors.regex.has_log_for_app.output
        output = loki.write.loki_b.input
      }
      route "other_logs_to_loki_a" {
        input  = processors.regex.not_log_for_app.output
        output = loki.write.loki_a.input
      }