service:
  type: NodePort
alloy:
  configMap:
    create: true
    # 여기다 Alloy config를 넣음 (indentation 주의! | 반드시 필요)
    
    content: |
      loki.source.file "spring_io_log_for_app" {
        path = ["/var/log/containers/*spring-io*.log"]
        include = ["*LOG_FOR_APP*"]
        forward_to = [loki.write.loki_b.receiver]
      }

      loki.process "spring_io_log_for_app" {
        path = ["/var/log/containers/*spring-a*.log"]
        exclude = ["*LOG_FOR_APP*"]
        forward_to = [loki.write.loki_a.receiver]
      }

      loki.write "loki_a" {
        endpoint {
          url = "http://loki.logging:3100/loki/api/v1/push"
        }
      }
      loki.write "loki_b" {
        endpoint {
          url = "http://loki-distributed-gateway.logging:3100/loki/api/v1/push"
        }
      }
  mounts:
    varlog: true      