authentik:
  postgresql:
    enabled: true
    auth:
      password: "changeme"


  replicaCount: 1
  service:
    type: NodePort
    nodePorts:
      http: 30080
    externalTrafficPolicy: Local
  config:
    entries:
      - key: server-snippet
        value: |
          location / {
            auth_request /auth;
            proxy_pass http://spring-io-service.spring-io.svc.cluster.local:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Original-URI $request_uri;
          }
          location = /auth {
            internal;
            proxy_pass http://authentik-server.auth-proxy.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
          }
