apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shared-ingress
  namespace: nginx
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: ing-shared-alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-certificate-no: "18031"
    alb.ingress.kubernetes.io/subnet-id: "34873"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/backend-protocol: HTTP

    alb.ingress.kubernetes.io/actions.nginx-service: >
      {"type":"targetGroup","targetGroup":{"targetGroups":[{"serviceName":"nginx/nginx-service","servicePort":80,"weight":100}]}}

    alb.ingress.kubernetes.io/actions.prometheus-server: >
      {"type":"targetGroup","targetGroup":{"targetGroups":[{"serviceName":"monitoring/prometheus-server","servicePort":80,"weight":100}]}}

    alb.ingress.kubernetes.io/actions.spring-route: >
      {"type":"targetGroup","targetGroup":{"targetGroups":[{"serviceName":"spring-io/spring-io-service","servicePort":80,"weight":100}]}}

    alb.ingress.kubernetes.io/actions.tempo: >
      {"type":"targetGroup","targetGroup":{"targetGroups":[{"serviceName":"observability/tempo","servicePort":3100,"weight":100}]}}

spec:
  ingressClassName: alb
  tls:
    - hosts:
        - y-nginx.aidtclass.com
        - y-spring-io.aidtclass.com
        - y-prometheus.aidtclass.com
        - y-tempo.aidtclass.com    
  rules:
    - host: y-nginx.aidtclass.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  name: use-annotation

    - host: y-prometheus.aidtclass.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-server
                port:
                  name: use-annotation

    - host: y-spring-io.aidtclass.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-route
                port:
                  name: use-annotation

    - host: y-tempo.aidtclass.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tempo
                port:
                  name: use-annotation             