apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shared-ingress
  namespace: nginx
  # annotations:
  #   alb.ingress.kubernetes.io/load-balancer-name: ing-shared-alb
  #   alb.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  ingressClassName: alb
  tls:
    - hosts:
        - y-prometheus.aidtclass.com
  rules:
    - host: y-prometheus.aidtclass.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-server
                port:
                  name: use-annotation