global:
  dnsService: "coredns"
  dnsNamespace: "kube-system"
  clusterDomain: "cluster.local"

loki:
  mode: distributed

distributor:
  replicas: 2
  maxUnavailable: 1  

ingester:
  replicas: 3
  maxUnavailable: 1

querier:
  replicas: 2
  maxUnavailable: 1    

queryFrontend:
  replicas: 2
  maxUnavailable: 1  

compactor:
  enabled: true

gateway:
  enabled: true

memberlist:
  service:
    publishNotReadyAddresses: true

serviceMonitor:
  enabled: true
  labels:
    release: prometheus

resources:
  requests:
    memory: 512Mi
  limits:
    memory: 1Gi
