projects:
  infra:
    namespace: argocd
    description: 인프라 환경
    sourceRepos:
      - '*'
    destinations:              # 배포를 허용할 대상
      - name: 'local'
        server: https://kubernetes.default.svc
        namespace: infra
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
    roles:
      - name: admin
        groups: [admin]
        policies:
          - p, proj:infra:admin, *, *, *, allow

  lms:
    namespace: argocd
    description: Learning-management-system services
    sourceRepos:
      - '*'
    destinations:
      - name: 'local'
        server: https://kubernetes.default.svc
        namespace: lms
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
    roles:
      - name: dev
        groups: [be-developer]
        policies:
          - p, proj:lms:dev, *, *, lms/*, allow
      - name: admin
        groups: [admin]
        policies:
          - p, proj:lms:admin, *, *, *, allow

  cdn:
    namespace: argocd
    description: FE CDN Deploy
    sourceRepos:
      - '*'
    destinations:
      - name: 'local'
        server: https://kubernetes.default.svc
        namespace: lms
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
    roles:
      - name: dev
        groups: [fe-developer]
        policies:
          - p, proj:cdn:dev, *, *, cdn/*, allow
      - name: admin
        groups: [admin]
        policies:
          - p, proj:cdn:admin, *, *, *, allow

applications:
  lms-guestbook:                 # ← Helm 릴리스-내 Application 이름
    namespace: argocd            # Application CR 자체가 존재할 네임스페이스
    project: lms                 # 위에서 정의한 AppProject
    source:
      repoURL: https://github.com/argoproj/argocd-example-apps.git
      targetRevision: HEAD       # 또는 main
      path: guestbook
      directory:
        recurse: true            # 서브 디렉터리 포함
    destination:
      server: https://kubernetes.default.svc
      namespace: lms
    syncPolicy:
      automated:
        prune: true              # 불필요 리소스 제거
        selfHeal: true           # 드리프트 자동 복구
      syncOptions:
        - CreateNamespace=true   # lms 네임스페이스가 없으면 생성
    revisionHistoryLimit: 3
    ignoreDifferences: []        # 필요 시 커스터마이즈
    info:
      - name: url
        value: https://argoproj.github.io/

applicationsets:
  infra-environments:
    namespace: argocd
    generators:
      - matrix:
          generators:
            - list:
                elements:
                  - cluster: in-cluster
            - list:
                elements:
                  - env: dev
                  - env: prod
                  - env: stag
    template:
      metadata:
        name: '{{cluster}}-{{env}}-infra'
      spec:
        project: default
        source:
          repoURL: https://github.com/Wizlit-Org/msa-logging.git
          targetRevision: main
          path: argocd_apps/{{cluster}}/{{env}}
        destination:
          server: https://kubernetes.default.svc
          namespace: '{{env}}'
        syncPolicy:
          automated:
            prune: true
            selfHeal: true

itemTemplates: []
extensions: {}