apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-proxy.fullname" . }}
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location / {
        auth_request /auth;
        proxy_pass {{ .Values.backend.url }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Original-URI $request_uri;
      }

      location = /auth {
        internal;
        proxy_pass {{ .Values.authentik.authURL }};
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Original-URI $request_uri;
      }
    }
