# values-override.yaml
server:
  configReloader:
    enable: true
  service:
    type: NodePort
  global:
    scrape_interval: 60s

  # https://yuys1.grafana.net/
  remoteWrite:
    - url: https://prometheus-prod-49-prod-ap-northeast-0.grafana.net/api/prom/push
      basic_auth:
        username: "2363713"
        password: "<GRAFANA_PASSWORD>"

extraScrapeConfigs: |
  - job_name: 'nginx-exporter'
    scrape_interval: 30s
    static_configs:
      - targets:
        - nginx-metrics.nginx.svc.cluster.local:9113

  - job_name: 'keda-operator-metrics-apiserver'
    scrape_interval: 30s
    static_configs:
      - targets:
          - keda-operator-metrics-apiserver.keda.svc.cluster.local:8080

  - job_name: 'keda-operator'
    scrape_interval: 30s
    static_configs:
      - targets:
          - keda-operator.keda.svc.cluster.local:8080

  - job_name: 'springboot-keda-apps'
    scrape_interval: 30s
    metrics_path: /actuator/prometheus 
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      # 필터: 라벨에 managed-by=keda
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_managed_by]
        regex: keda
        action: keep

      # 필터: 라벨에 keda-enabled=true
      - source_labels: [__meta_kubernetes_service_label_keda_enabled]
        regex: true
        action: keep

      # 필터: app.kubernetes.io.name 이 "keda-spring" 인 경우만 포함
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
        regex: keda-spring
        action: keep

      # 잡 이름(label) 설정
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
        target_label: app

      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace

      - source_labels: [__meta_kubernetes_service_name]
        target_label: service

      - source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: http|web|metrics
        action: keep