ingester:
  replicas: 1
ruler_querier:
  replicas: 1
ruler_query_scheduler:
  replicas: 1
querier:
  replicas: 1
query_scheduler:
  replicas: 1

gateway:
  enabled: false
alertmanager:
  enabled: false
distributor:
  enabled: false  
store_gateway:
  enabled: true
