# Grafana 설치용 values.yaml (NKS 내부에서 Prometheus + Tempo 자동 연결)
# Namespace: observability

adminUser: admin
adminPassword: admin123

service:
  enabled: true
  type: NodePort
  nodePort: 30030

persistence:
  enabled: true
  size: 5Gi

# Prometheus + Tempo 데이터소스 자동 등록
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local:80
        isDefault: true

      - name: Loki
        type: loki
        access: proxy
        url: http://loki.logging.svc.cluster.local:3100
        isDefault: false

      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3100
        jsonData:
          httpMethod: GET
          tracesToLogs:
            datasourceUid: 'loki'  # 사용 중이라면 Loki UID에 맞게 수정
            mapTagNamesEnabled: true
            mappedTags:
              - key: 'service.name'
                value: 'spring-app'
            spanStartTimeShift: '1h'
            spanEndTimeShift: '1h'
            filterByTraceID: true
            filterBySpanID: false
          serviceMap:
            datasourceUid: 'prometheus'
          nodeGraph:
            enabled: true
          search:
            hide: false
          lokiSearch:
            datasourceUid: 'loki'        

sidecar:
  dashboards:
    enabled: true
