---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/managed-by: keda
    keda-enabled: "true"    
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to nginx!</title>
    </head>
    <body>
        <h1>Hello</h1>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-entrypoint
  namespace: nginx
data:
  entrypoint.sh: |
    #!/bin/sh
    envsubst '$AUTHENTIK_DOMAIN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
    exec nginx -g 'daemon off;'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-template
  namespace: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/managed-by: keda
    keda-enabled: "true"    
data:
  nginx.conf.template: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        # log_format  main  '$remote_addr - $proxy_protocol_addr -$remote_user [$time_local] "$request" '
        #                   '$status $body_bytes_sent "$http_referer" '
        #                   '"$http_user_agent" "$http_x_forwarded_for"';
        log_format main '$remote_addr - $remote_user [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent" '
                        'realip:$http_x_forwarded_for';        

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        keepalive_timeout  65;

        # Upgrade WebSocket if requested, otherwise use keepalive
        map $http_upgrade $connection_upgrade_keepalive {
            default upgrade;
            ''      '';
        }

        server {
            listen 80;

            # ALB에서 오는 트래픽의 IP 대역 (예: NCP ALB 내부 서브넷)
            # 실제 client IP는 ALB가 넣어주는 X-Forwarded-For에 있음
            set_real_ip_from 198.18.0.0/16;
            real_ip_header X-Forwarded-For;     

            proxy_buffers 8 16k;
            proxy_buffer_size 32k;

            location / {

                # Put your proxy_pass to your application here, and all the other statements you'll need
                # proxy_pass http://localhost:5000;
                # proxy_set_header Host $host;
                # proxy_set_header ...
                # Support for websocket
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade_keepalive;
            
                ##############################
                # authentik-specific config
                ##############################
                auth_request     /outpost.goauthentik.io/auth/nginx;
                error_page       401 = @goauthentik_proxy_signin;
                auth_request_set $auth_cookie $upstream_http_set_cookie;
                add_header       Set-Cookie $auth_cookie;

                # translate headers from the outposts back to the actual upstream
                auth_request_set $authentik_username $upstream_http_x_authentik_username;
                auth_request_set $authentik_groups $upstream_http_x_authentik_groups;
                auth_request_set $authentik_entitlements $upstream_http_x_authentik_entitlements;
                auth_request_set $authentik_email $upstream_http_x_authentik_email;
                auth_request_set $authentik_name $upstream_http_x_authentik_name;
                auth_request_set $authentik_uid $upstream_http_x_authentik_uid;

                proxy_set_header X-authentik-username $authentik_username;
                proxy_set_header X-authentik-groups $authentik_groups;
                proxy_set_header X-authentik-entitlements $authentik_entitlements;
                proxy_set_header X-authentik-email $authentik_email;
                proxy_set_header X-authentik-name $authentik_name;
                proxy_set_header X-authentik-uid $authentik_uid;

                root   /usr/share/nginx/html;
                index  index.html index.htm;

                # 클라이언트 IP를 백엔드로 전달
                proxy_set_header X-Real-IP       $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
            }

            location /my-ip {
                default_type text/html;
                return 200 "<html><body><h1>Your IP: $remote_addr</h1><h1>Your IP: $http_x_forwarded_for</h1></body></html>";
            }

            location /outpost.goauthentik.io {
                # When using the embedded outpost, use:
                proxy_pass https://${AUTHENTIK_DOMAIN}/outpost.goauthentik.io;

                # Note: ensure the Host header matches your external authentik URL:
                proxy_set_header Host $host;

                proxy_set_header        X-Original-URL $scheme://$http_host$request_uri;
                add_header              Set-Cookie $auth_cookie;
                auth_request_set        $auth_cookie $upstream_http_set_cookie;
                proxy_pass_request_body off;
                proxy_set_header        Content-Length "";
            }

          # Special location for when the /auth endpoint returns a 401,
          # redirect to the /start URL which initiates SSO
            location @goauthentik_proxy_signin {
                internal;
                add_header Set-Cookie $auth_cookie;
                return 302 /outpost.goauthentik.io/start?rd=$scheme://$http_host$request_uri;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }

        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/managed-by: keda
    keda-enabled: "true"     
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/name: nginx
        app.kubernetes.io/managed-by: keda        
    spec:
      containers:
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:latest
          args:
            - -nginx.scrape-uri=http://localhost/nginx_status
          ports:
            - containerPort: 9113      
        - name: nginx
          image: nginx:latest
          command: ["/bin/sh", "-c"]
          args: ["/entrypoint.sh"]
          env:
            - name: AUTHENTIK_DOMAIN
              value: authentik-server.auth-proxy.svc.cluster.local
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: nginx-conf-template
              mountPath: /etc/nginx/nginx.conf.template
              subPath: nginx.conf.template
            - name: nginx-entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh    
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
          ports:
            - containerPort: 80
      volumes:
        - name: html-volume
          configMap:
            name: nginx-index
        - name: nginx-conf-template
          configMap:
            name: nginx-conf-template
        - name: nginx-entrypoint
          configMap:
            name: nginx-entrypoint
            defaultMode: 0755          
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/managed-by: keda
    keda-enabled: "true"    
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
# nginx-exporter
apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics
  namespace: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/managed-by: keda
    keda-enabled: "true"    
spec:
  selector:
    app: nginx
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113
  type: ClusterIP