global:
  domain: y-argocd.${DOMAIN}

dex:
  enabled: false

notifications:
  enabled: true
  argocdUrl: "https://y-argocd.${DOMAIN}"
  notifiers:
    service.slack: |
      token: ${SLACK_TOKEN}

configs:
  cm:
    kustomize.buildOptions: "--enable-helm"  
    admin.enabled: true
    exec.enabled: true
    statusbadge.enabled: true
    ui.bannercontent: "이 환경은 테스트를 위해 임시로 설치되었습니다. (공공 남부)"
    ui.bannerposition: "bottom"
    application.links: |
      - name: Dev Project
        url:  https://t-argocd.${DOMAIN}/applications/argocd/{{ .metadata.name }}?search={{ .metadata.namespace }}
        iconClass: fa fa-rocket
      - name: BETA Project
        url:  https://t-argocd.${DOMAIN}/applications?proj=beta
        iconClass: fa fa-vial

    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.${DOMAIN}/auth/realms/visang.com
      clientID: oidc.y-argocd.${DOMAIN}
      clientSecret: $oidc.keycloak.clientSecret
      logoutURL: https://keycloak.${DOMAIN}.com/auth/realms/visang.com/protocol/openid-connect/logout?redirect_uri=https://y-argocd.aidtclass.com
      requestedIDTokenClaims:
        roles:
          essential: true  
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email

    accounts.codebplat: apiKey,login
    accounts.codebplat.enabled: "true"
    accounts.dsymong: apiKey,login
    accounts.dsymong.enabled: "true"
    accounts.ggp: apiKey,login
    accounts.ggp.enabled: "true"

  rbac:
    create: true
    scopes: '[groups, roles]'    
    policy.default: role:none
    policy.csv: |

      # ───── Claim → 전역 Role 매핑 ─────
      g, /관리자,                                     role:admin
      g, /비상/콘텐츠/에듀테크/클라우드 개발 Cell,        role:admin
      g, /비상/콘텐츠/에듀테크/BE개발 Cell,              role:visang

      g, be-developer,                     role:be-developer
      g, fe-developer,                     role:fe-developer
      g, /비상/콘텐츠/외주사/GGP,             role:fe-developer
      g, socket-developer,                 role:socket-developer
      g, grp-developer,                    role:grp-developer
      g, /비상/콘텐츠/외주사/코드비플랫,       role:grp-developer
      g, /비상/콘텐츠/외주사/GGP,            role:grp-developer

      # ───── 전역 Role → 권한 정의 ─────
      p, role:admin, *, *, *, allow
      p, role:visang, applications, get, *, allow
      p, role:visang, applications, sync, *, allow
      p, role:visang, applications, logs, *, allow  

      p, role:be-developer,     applications, *,       lms/*,       allow
      p, role:fe-developer,     applications, *,       cdn/*,       allow
      p, role:socket-developer, applications, *,       socket/*,    allow
      p, role:socket-developer, applications, *,       cdn/*,       allow
      p, role:grp-developer,    applications, *,       tutorus/*,   allow
      p, role:grp-developer,    exec,          create, tutorus/*,   allow

  repositories:
    pubedutdc-vsaidt-helm-repo:
      url: https://gitlab.aidtclass.com/pubedutdc/vsaidt-helm-chart.git
      type: git
      name: pubedutdc-vsaidt-helm-repo
      username: "git-bot-client"
      password: "Qltkdrydbr!12"
      project: default

    pubedutdc-argocd-manifest-default:
      url: https://gitlab.aidtclass.com/pubedutdc/argocd_manifest.git
      type: git
      name: pubedutdc-argocd-manifest-default
      username: "git-bot-client"
      password: "Qltkdrydbr!12"
      project: default

    pubedutdc-kube-config:
      url: https://gitlab.aidtclass.com/pubedutdc/kube_configmap.git
      type: git
      name: pubedutdc-kube-config
      username: "git-bot-client"
      password: "Qltkdrydbr!12"
      project: default

    pubedutdc-argocd-manifest-dev:
      url: https://gitlab.aidtclass.com/pubedutdc/argocd_manifest.git
      type: git
      name: pubedutdc-argocd-manifest-dev
      username: "git-bot-client"
      password: "Qltkdrydbr!12"
      project: dev

    visang-cloud-k8s-infra:
      url: https://gitlab.aidtclass.com/visang-cloud/k8s-infra.git
      type: git
      name: visang-cloud-k8s-infra
      username: "git-bot-client"
      password: "Qltkdrydbr!12"
      project: infra

    pubedutdc-argocd-manifest-tutorus:
      url: https://gitlab.aidtclass.com/pubedutdc/argocd_manifest.git
      type: git
      name: pubedutdc-argocd-manifest-tutorus
      username: "git-bot-client"
      password: "Qltkdrydbr!12"
      project: tutorus


  projects:
    beta:
      description: "베타 환경"
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: '*'
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'

    beta2:
      description: "베타2"
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: '*'

    beta2-tutorus:
      description: "베타2 튜터러스"
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: '*'

    cdn:
      description: "fe cdn deploy"
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: '*'

    default:
      description: ""
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: '*'

    dev:
      description: "dev"
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: '*'

    infra:
      description: "인프라 환경"
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: '*'

    release:
      description: "릴리즈 환경"
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: '*'

    stg:
      description: "stg"
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: '*'

    stg1:
      description: "stg1 ....."
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: '*'

    tutorus:
      description: "튜터러스+밸브 AI 기능"
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: '*'

    whiteboard:
      description: "화이트보드"
      sourceRepos:
        - '*'
      destinations:
        - namespace: '*'
          server: '*'

  secret:
    createSecret: true
    argocdServerAdminPassword: "$2a$12$9vgR3l98J4XFDMuHQBe03uXAAg6r4cW7ZI04PbHK8O0VOQttULedW"
    extra:
      oidc.keycloak.clientSecret: LdXcgFKGJItJKREcFvcbjWoKiQwDThtg

applicationSet:
  enabled: true

redis:
  enabled: true
  persistence:
    enabled: true
    storageClass: standard
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi
  exporter:
    enabled: false

redis-ha:
  enabled: false
  persistentVolume:
    enabled: false

server:
  service:
    type: NodePort
  ingress:
    enabled: false
    ingressClassName: "nginx"

    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "${DOMAIN}-issuer"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true" 

    extraTls:
      - hosts:
        - y-argocd.${DOMAIN}
        secretName: argocd-tls

  extraArgs:
    - --insecure

  ## Argo CD extensions
  ## This function in tech preview stage, do expect instability or breaking changes in newer versions.
  ## Ref: https://github.com/argoproj-labs/argocd-extension-installer
  ## When you enable extensions, you need to configure RBAC of logged in Argo CD user.
  ## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/#the-extensions-resource
  extensions:
    enabled: true

  resources:
    limits:
      cpu: 2
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

controller:
  resources:
    limits:
      cpu: 2
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

repoServer:
  persistence:
    enabled: true
    storageClass: standard
  resources:
    limits:
      cpu: 2
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi