apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-b
  namespace: spring-b  
  labels:
    app: spring-b
    deployment_environment_name: dev    
    app.kubernetes.io/name: keda-spring
    app.kubernetes.io/managed-by: keda
    keda-enabled: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-b
  template:
    metadata:
      labels:
        app: spring-b
        deployment_environment_name: dev        
        app.kubernetes.io/name: keda-spring
        app.kubernetes.io/managed-by: keda
        keda-enabled: "true"        
    spec:
      terminationGracePeriodSeconds: 40    
      containers:
      - name: spring-b
        image: dev.local/spring-b:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: APP_NAME
          value: spring-b
        - name: SPRING_URL
          value: spring-a-service.spring-a.svc.cluster.local        
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OTEL_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OTEL_K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: OTEL_K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OTEL_K8S_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=$(OTEL_K8S_NAMESPACE),service.node.name=$(OTEL_K8S_NODE_NAME),deployment.environment=dev"
        - name: OTEL_RESOURCE_ATTRIBUTES_DEPLOYMENT_ENVIRONMENT
          value: "dev"
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        - name: OTEL_LOGS_EXPORTER
          value: otlp
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4318
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: http/protobuf     
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
---
apiVersion: v1
kind: Service
metadata:
  name: spring-b-service
  namespace: spring-b  
  labels:
    app: spring-b
    deployment_environment_name: dev    
    app.kubernetes.io/name: keda-spring
    app.kubernetes.io/managed-by: keda
    keda-enabled: "true"
spec:
  selector:
    app: spring-b
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort      