mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  exporters:
    otlp/tempo:
      endpoint: tempo-distributor.observability.svc.cluster.local:4317
      tls:
        insecure: true

  service:
    pipelines:
      logs:
        receivers: [otlp]
        exporters: [loki]

      traces:
        receivers: [otlp]
        exporters: [otlp/tempo]        