mode: daemonset
image:
  repository: otel/opentelemetry-collector-contrib
  # repository: otel/opentelemetry-collector-k8s
  tag: latest

ports:
  metrics:
    enabled: true

presets:
  hostMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
    prometheus:
      config:
        scrape_configs:
          - job_name: "spring"
            scrape_interval: 10s
            metrics_path: /actuator/prometheus
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_managed_by]
                regex: keda
                action: keep
              
  exporters:
    debug:
      verbosity: detailed
    prometheusremotewrite:
      endpoint: http://prometheus-server.monitoring.svc.cluster.local:80/api/v1/write  
      resource_to_telemetry_conversion:
        enabled: true      
      tls:
        insecure: true
    loki:
      endpoint: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push  # Promtail 또는 직접 로그 export
      tls:
        insecure: true    
    otlphttp:
      endpoint: http://tempo.observability.svc.cluster.local:4318
      tls:
        insecure: true
  service:
    pipelines:
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [loki]
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlphttp]
      metrics:
        receivers: [prometheus]
        processors: [k8sattributes, batch]
        exporters: [prometheusremotewrite, debug]
  processors:
    k8sattributes:
      auth_type: serviceAccount
      extract:
        metadata:
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.deployment.name
          - k8s.node.name
          - container.id
    batch:
      send_batch_size: 10000
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25

clusterRole:
  create: true