mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest  

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  exporters:
    debug: {}  # 단순히 Collector 로그로 출력해보기 위함
    prometheusremotewrite:
      endpoint: http://prometheus-server.monitoring.svc.cluster.local:80/api/v1/write
      tls:
        insecure: true
    loki:
      endpoint: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
      tls:
        insecure: true    
    otlp/tempo:
      endpoint: tempo.observability.svc.cluster.local:4317
      tls:
        insecure: true

  service:
    pipelines:
      logs:
        receivers: [otlp]
        exporters: [debug, loki]

      traces:
        receivers: [otlp]
        exporters: [debug, otlp/tempo]

      metrics:
        receivers: [otlp]
        processors: [resource, batch]
        exporters: [prometheusremotewrite]        

  processors:
    resource:
      attributes:
        - action: insert
          key: service.name
          from_attribute: service.name
        - action: insert
          key: k8s.namespace.name
          from_attribute: k8s.namespace.name
        - action: insert
          key: k8s.pod.name
          from_attribute: k8s.pod.name