mode: daemonset
image:
  repository: otel/opentelemetry-collector-contrib
  # repository: otel/opentelemetry-collector-k8s
  tag: latest

ports:
  metrics:
    enabled: true

presets:
  hostMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
    prometheus:
      config:
        scrape_configs:
        - job_name: 'springboot-keda-apps'
          scrape_interval: 10s
          metrics_path: "/actuator/prometheus"
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            # 필터링: app.kubernetes.io/managed-by=keda
            - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_managed_by]
              regex: keda
              action: keep
            # 라벨 복사
            - source_labels: [__meta_kubernetes_service_label_deployment_environment_name]
              target_label: deployment_environment_name
            - source_labels: [__meta_kubernetes_service_name]
              target_label: service_name
            - source_labels: [__meta_kubernetes_namespace]
              target_label: service_namespace              
  exporters:
    debug:
      verbosity: detailed
    prometheusremotewrite:
      endpoint: http://prometheus-server.monitoring.svc.cluster.local:80/api/v1/write  
      resource_to_telemetry_conversion:
        enabled: true      
      tls:
        insecure: true
    loki:
      endpoint: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push  # Promtail 또는 직접 로그 export
      tls:
        insecure: true    
    otlphttp:
      endpoint: http://tempo.observability.svc.cluster.local:4318
      tls:
        insecure: true
  service:
    pipelines:
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [loki]
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlphttp]
      metrics:
        receivers: [prometheus]
        processors: [resource, batch]
        exporters: [prometheusremotewrite, debug]
  processors:
    attributes:
      actions:
        - action: insert
          key: loki.attribute.labels
          value: exporter, stream, detected, level, logger, service_node_name
    resource:
      attributes:
      - action: insert
        key: loki.format
        value: raw
      - action: insert
        key: service_node_name
        from_attribute: service.node
      - action: insert
        key: deployment_environment_name
        from_attribute: deployment.environment
      - action: insert
        key: loki.resource.labels
        value: service_node_name, exporter, stream, detected, level, logger
    batch:
      send_batch_size: 10000
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25

clusterRole:
  create: true      