mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  exporters:
    debug: {}  # 단순히 Collector 로그로 출력해보기 위함  
    otlp/tempo:
      endpoint: tempo-distributor.observability.svc.cluster.local:4317
      tls:
        insecure: true

  service:
    pipelines:
      logs:
        receivers: [otlp]
        exporters: [debug]

      traces:
        receivers: [otlp]
        exporters: [debug, otlp/tempo]