mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  exporters:
    debug: {}  # 단순히 Collector 로그로 출력해보기 위함
    loki:
      endpoint: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
      tls:
        insecure: true    
    otlp/tempo:
      endpoint: tempo.observability.svc.cluster.local:4317
      tls:
        insecure: true

  service:
    pipelines:
      logs:
        receivers: [otlp]
        exporters: [debug, loki]

      traces:
        receivers: [otlp]
        exporters: [debug, otlp/tempo]