apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
spec:
  project: default
  source:
    repoURL: https://github.com/Wizlit-Org/msa-logging.git
    targetRevision: main
    path: cert-manager
    helm:
      valueFiles:
        - values-override.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true