apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: prometheus
spec:
  project: default
  source:
    repoURL: https://github.com/Wizlit-Org/msa-logging.git
    targetRevision: main
    path: prometheus-operator
    helm:
      valueFiles:
        - values-override.yaml          
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true