# Configuration for the metrics-generator
metricsGenerator:
  enabled: true

traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true

queryFrontend:
  query:
    enabled: false
  service:
    type: NodePort
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: y-tempo.vsaidt.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: tempo-query-tls
        hosts:
          - query.tempo.vsaidt.com
